[project]
name = "ocr-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docling>=2.60.1",
    "mistralai>=1.9.11",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
]
